//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class alisveriDetay
    {
        public int alisverisDetayId { get; set; }
        public Nullable<int> uyeId { get; set; }
        public string adres { get; set; }
        public string sehir { get; set; }
        public string cadde { get; set; }
        public string ulke { get; set; }
        public string postaKodu { get; set; }
        public Nullable<int> siparisId { get; set; }
        public Nullable<decimal> odenenMiktar { get; set; }
        public string odemeTuru { get; set; }
    
        public virtual uyeTable uyeTable { get; set; }
    }
}
