//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class kartTable
    {
        public int kartId { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> uyeId { get; set; }
        public Nullable<int> kartStatuId { get; set; }
    
        public virtual urunTable urunTable { get; set; }
    }
}
