//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunTable()
        {
            this.kartTables = new HashSet<kartTable>();
        }
    
        public int urunId { get; set; }
        public string urunAdi { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public Nullable<System.DateTime> eklenmeTarihi { get; set; }
        public Nullable<System.DateTime> degisimTarihi { get; set; }
        public string aciklama { get; set; }
        public string urunResmi { get; set; }
        public Nullable<bool> ozellik { get; set; }
        public Nullable<int> miktar { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kartTable> kartTables { get; set; }
        public virtual kategoriTable kategoriTable { get; set; }
    }
}
