//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uyeTable()
        {
            this.alisveriDetays = new HashSet<alisveriDetay>();
        }
    
        public int uyeId { get; set; }
        public string uyeAd { get; set; }
        public string uyeSoyad { get; set; }
        public string uyeEmail { get; set; }
        public string uyePass { get; set; }
        public Nullable<System.DateTime> uyelikTarihi { get; set; }
        public Nullable<System.DateTime> uyelikDegismeTarihi { get; set; }
        public string uyeRol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alisveriDetay> alisveriDetays { get; set; }
    }
}
